### ISSUE TITLE
兼容星号 * 这个 markdown 语法

### ISSUE THREAD

**Issue by chenglu** [huacnlee/auto-correct#15]
图个方便，我直接分享在 auto-correct 的 go playground 里的结果：
https://play.golang.org/p/f3KcYNh2Mnp

看起来当我想使用 ```**``` 给 Markdown 字体加粗的时候，它被「无情」的加入了空格导致失效。

![image](https://user-images.githubusercontent.com/2258420/96201814-24ada880-0f90-11eb-9ec8-e098fe7eda23.png)

不知道这个 issue 的场景是否合理，针对这个问题是否可以帮助看一下如何处理？

谢谢 @huacnlee !

**Comment by huacnlee** [comment]
先 Markdown -> HTML 然后再使用

**Comment by chenglu** [comment]
谢谢 Jason 的回复，是个好主意，不过这个场景的目标是在 Discourse 论坛里，印象里可能数据库里只能存放 Markdown 的格式内容。

我主要是通过 瑪麗蘇 老师开发的 Discourse 插件 discourse-cjk-text-spacing 实现中英文之间的空格，也有一些探讨在这里 https://github.com/openSUSE-zh/discourse-cjk-text-spacing/issues/1

不知道是否有什么更好的主意和思路嘛？

再次感谢 @huacnlee ！

**Comment by huacnlee** [comment]
你可以看看 Homeland 的实现，内容格式化是在展示的时候做的，全站所有内容都有开启。

不仅是 Ruby China，我们还把 auto-correct 用在我们公司各类业务里面，也是全部处理的。

**Comment by chenglu** [comment]
明白，内容格式化要是在前端展示的时候，通过 ```format_html``` 进行格式化，那应该碰不上我现在的这个问题。那我再看看其他解决办法吧，感谢。

p.s. Use cases 应该可以更新为：Ruby China 目前整站的内容都做了自动转换处理 ;-)
